version: '3'
services:

  ictlab_front:
    restart: unless-stopped
    image: nginx:latest
    volumes:
      - ./ictlab-front.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/app:ro
    networks:
      - newix_net
    ports:
      - 127.0.0.1:8080:80
    depends_on:
     - ictlab_back

networks:
  newix_net:
    name: newix_net
    