version: '3'
services:

  ictlab_front:
    image: nginx:latest
    volumes:
      - ./certbot.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/certbot
    ports:
      - "80:80"

  ictlab_certbot:
    image: certbot/certbot:latest
    entrypoint: sh /get-cert.sh
    volumes:
      - ./script/get-cert.sh:/get-cert.sh
      - ./conf/:/etc/letsencrypt
      - ./logs/:/var/log/letsencrypt
      - ./www:/var/www/certbot
    depends_on:
      - ictlab_front
